"""initial water network domain

Revision ID: 6ab623113c1c
Revises: 
Create Date: 2026-10-03 08:28:23.401463

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import geoalchemy2


# revision identifiers, used by Alembic.
revision: str = '6ab623113c1c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('network_node',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('node_type', sa.Enum('RESERVOIR', 'TREATMENT_PLANT', 'DEMAND_ZONE', 'CRITICAL_FACILITY', name='node_type'), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography', nullable=False), nullable=False),
    sa.Column('status', sa.Enum('OPERATIONAL', 'DEGRADED', 'OFFLINE', 'MAINTENANCE', name='asset_status'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_network_node')),
    sa.UniqueConstraint('code', name=op.f('uq_network_node_code'))
    )
    op.create_index('ix_network_node_location', 'network_node', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_network_node_node_type'), 'network_node', ['node_type'], unique=False)
    op.create_index(op.f('ix_network_node_status'), 'network_node', ['status'], unique=False)
    op.create_table('demand_zone',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('boundary', geoalchemy2.types.Geography(geometry_type='MULTIPOLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('zone_type', sa.Enum('RESIDENTIAL', 'COMMERCIAL', 'INDUSTRIAL', 'MIXED', 'AGRICULTURAL', name='zone_type'), nullable=False),
    sa.Column('population', sa.Integer(), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='priority_level'), nullable=False),
    sa.Column('demand_m3_per_day', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('minimum_demand_m3_per_day', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('local_storage_m3', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('stored_volume_m3', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.CheckConstraint('demand_m3_per_day >= 0', name=op.f('ck_demand_zone_demand_non_negative')),
    sa.CheckConstraint('local_storage_m3 >= 0', name=op.f('ck_demand_zone_local_storage_non_negative')),
    sa.CheckConstraint('minimum_demand_m3_per_day >= 0 AND minimum_demand_m3_per_day <= demand_m3_per_day', name=op.f('ck_demand_zone_minimum_demand_within_demand')),
    sa.CheckConstraint('population >= 0', name=op.f('ck_demand_zone_population_non_negative')),
    sa.CheckConstraint('stored_volume_m3 >= 0 AND stored_volume_m3 <= local_storage_m3', name=op.f('ck_demand_zone_stored_volume_within_storage')),
    sa.ForeignKeyConstraint(['id'], ['network_node.id'], name=op.f('fk_demand_zone_id_network_node'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_demand_zone'))
    )
    op.create_index('ix_demand_zone_boundary', 'demand_zone', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_demand_zone_priority'), 'demand_zone', ['priority'], unique=False)
    op.create_table('pipeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('source_node_id', sa.Integer(), nullable=False),
    sa.Column('target_node_id', sa.Integer(), nullable=False),
    sa.Column('capacity_m3_per_day', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('current_flow_m3_per_day', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('loss_ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('length_m', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('diameter_mm', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('bidirectional', sa.Boolean(), nullable=False),
    sa.Column('status', sa.Enum('OPERATIONAL', 'DEGRADED', 'OFFLINE', 'MAINTENANCE', name='asset_status'), nullable=False),
    sa.Column('route', geoalchemy2.types.Geography(geometry_type='LINESTRING', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('capacity_m3_per_day > 0', name=op.f('ck_pipeline_capacity_positive')),
    sa.CheckConstraint('current_flow_m3_per_day >= 0 AND current_flow_m3_per_day <= capacity_m3_per_day', name=op.f('ck_pipeline_flow_within_capacity')),
    sa.CheckConstraint('diameter_mm IS NULL OR diameter_mm > 0', name=op.f('ck_pipeline_diameter_positive')),
    sa.CheckConstraint('length_m IS NULL OR length_m > 0', name=op.f('ck_pipeline_length_positive')),
    sa.CheckConstraint('loss_ratio >= 0 AND loss_ratio < 1', name=op.f('ck_pipeline_loss_ratio_fraction')),
    sa.CheckConstraint('source_node_id <> target_node_id', name=op.f('ck_pipeline_no_self_loop')),
    sa.ForeignKeyConstraint(['source_node_id'], ['network_node.id'], name=op.f('fk_pipeline_source_node_id_network_node'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['network_node.id'], name=op.f('fk_pipeline_target_node_id_network_node'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pipeline')),
    sa.UniqueConstraint('code', name=op.f('uq_pipeline_code')),
    sa.UniqueConstraint('source_node_id', 'target_node_id', name='unique_edge')
    )
    op.create_index('ix_pipeline_route', 'pipeline', ['route'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_pipeline_source_node_id'), 'pipeline', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_pipeline_status'), 'pipeline', ['status'], unique=False)
    op.create_index(op.f('ix_pipeline_target_node_id'), 'pipeline', ['target_node_id'], unique=False)
    op.create_table('reservoir',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity_m3', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('current_volume_m3', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('dead_storage_m3', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('max_withdrawal_m3_per_day', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('inflow_m3_per_day', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('water_quality', sa.Enum('RAW', 'TREATED', 'POTABLE', name='water_quality'), nullable=False),
    sa.CheckConstraint('capacity_m3 > 0', name=op.f('ck_reservoir_capacity_positive')),
    sa.CheckConstraint('current_volume_m3 >= 0 AND current_volume_m3 <= capacity_m3', name=op.f('ck_reservoir_volume_within_capacity')),
    sa.CheckConstraint('dead_storage_m3 >= 0 AND dead_storage_m3 <= capacity_m3', name=op.f('ck_reservoir_dead_storage_within_capacity')),
    sa.CheckConstraint('inflow_m3_per_day >= 0', name=op.f('ck_reservoir_inflow_non_negative')),
    sa.CheckConstraint('max_withdrawal_m3_per_day >= 0', name=op.f('ck_reservoir_max_withdrawal_non_negative')),
    sa.ForeignKeyConstraint(['id'], ['network_node.id'], name=op.f('fk_reservoir_id_network_node'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reservoir'))
    )
    op.create_table('tanker',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('capacity_m3', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('current_load_m3', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('cargo_quality', sa.Enum('RAW', 'TREATED', 'POTABLE', name='water_quality'), nullable=True),
    sa.Column('status', sa.Enum('IDLE', 'LOADING', 'EN_ROUTE', 'UNLOADING', 'MAINTENANCE', name='tanker_status'), nullable=False),
    sa.Column('average_speed_kmh', sa.Numeric(precision=6, scale=2), nullable=False),
    sa.Column('trips_per_day', sa.Integer(), nullable=False),
    sa.Column('current_location', geoalchemy2.types.Geography(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeogFromText', name='geography'), nullable=True),
    sa.Column('home_node_id', sa.Integer(), nullable=True),
    sa.Column('destination_node_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('average_speed_kmh > 0', name=op.f('ck_tanker_speed_positive')),
    sa.CheckConstraint('capacity_m3 > 0', name=op.f('ck_tanker_capacity_positive')),
    sa.CheckConstraint('current_load_m3 >= 0 AND current_load_m3 <= capacity_m3', name=op.f('ck_tanker_load_within_capacity')),
    sa.CheckConstraint('trips_per_day > 0', name=op.f('ck_tanker_trips_positive')),
    sa.ForeignKeyConstraint(['destination_node_id'], ['network_node.id'], name=op.f('fk_tanker_destination_node_id_network_node'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_node_id'], ['network_node.id'], name=op.f('fk_tanker_home_node_id_network_node'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tanker')),
    sa.UniqueConstraint('code', name=op.f('uq_tanker_code'))
    )
    op.create_index('ix_tanker_current_location', 'tanker', ['current_location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_tanker_destination_node_id'), 'tanker', ['destination_node_id'], unique=False)
    op.create_index(op.f('ix_tanker_home_node_id'), 'tanker', ['home_node_id'], unique=False)
    op.create_index(op.f('ix_tanker_status'), 'tanker', ['status'], unique=False)
    op.create_table('treatment_plant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity_m3_per_day', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('min_throughput_m3_per_day', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('current_throughput_m3_per_day', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('recovery_ratio', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('output_quality', sa.Enum('RAW', 'TREATED', 'POTABLE', name='water_quality'), nullable=False),
    sa.CheckConstraint('capacity_m3_per_day > 0', name=op.f('ck_treatment_plant_capacity_positive')),
    sa.CheckConstraint('current_throughput_m3_per_day >= 0 AND current_throughput_m3_per_day <= capacity_m3_per_day', name=op.f('ck_treatment_plant_throughput_within_capacity')),
    sa.CheckConstraint('min_throughput_m3_per_day >= 0 AND min_throughput_m3_per_day <= capacity_m3_per_day', name=op.f('ck_treatment_plant_min_throughput_within_capacity')),
    sa.CheckConstraint('recovery_ratio > 0 AND recovery_ratio <= 1', name=op.f('ck_treatment_plant_recovery_ratio_fraction')),
    sa.ForeignKeyConstraint(['id'], ['network_node.id'], name=op.f('fk_treatment_plant_id_network_node'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_treatment_plant'))
    )
    op.create_table('critical_facility',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('facility_type', sa.Enum('HOSPITAL', 'FIRE_STATION', 'SCHOOL', 'SHELTER', 'WATER_TREATMENT', 'POWER_PLANT', 'GOVERNMENT', name='facility_type'), nullable=False),
    sa.Column('priority', sa.Enum('CRITICAL', 'HIGH', 'MEDIUM', 'LOW', name='priority_level'), nullable=False),
    sa.Column('demand_m3_per_day', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('minimum_demand_m3_per_day', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('backup_storage_m3', sa.Numeric(precision=14, scale=3), nullable=False),
    sa.Column('service_population', sa.Integer(), nullable=False),
    sa.Column('demand_zone_id', sa.Integer(), nullable=True),
    sa.CheckConstraint('backup_storage_m3 >= 0', name=op.f('ck_critical_facility_backup_storage_non_negative')),
    sa.CheckConstraint('demand_m3_per_day >= 0', name=op.f('ck_critical_facility_demand_non_negative')),
    sa.CheckConstraint('minimum_demand_m3_per_day >= 0 AND minimum_demand_m3_per_day <= demand_m3_per_day', name=op.f('ck_critical_facility_minimum_demand_within_demand')),
    sa.CheckConstraint('service_population >= 0', name=op.f('ck_critical_facility_service_population_non_negative')),
    sa.ForeignKeyConstraint(['demand_zone_id'], ['demand_zone.id'], name=op.f('fk_critical_facility_demand_zone_id_demand_zone'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id'], ['network_node.id'], name=op.f('fk_critical_facility_id_network_node'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_critical_facility'))
    )
    op.create_index(op.f('ix_critical_facility_demand_zone_id'), 'critical_facility', ['demand_zone_id'], unique=False)
    op.create_index(op.f('ix_critical_facility_facility_type'), 'critical_facility', ['facility_type'], unique=False)
    op.create_index(op.f('ix_critical_facility_priority'), 'critical_facility', ['priority'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_critical_facility_priority'), table_name='critical_facility')
    op.drop_index(op.f('ix_critical_facility_facility_type'), table_name='critical_facility')
    op.drop_index(op.f('ix_critical_facility_demand_zone_id'), table_name='critical_facility')
    op.drop_table('critical_facility')
    op.drop_table('treatment_plant')
    op.drop_index(op.f('ix_tanker_status'), table_name='tanker')
    op.drop_index(op.f('ix_tanker_home_node_id'), table_name='tanker')
    op.drop_index(op.f('ix_tanker_destination_node_id'), table_name='tanker')
    op.drop_index('ix_tanker_current_location', table_name='tanker', postgresql_using='gist')
    op.drop_table('tanker')
    op.drop_table('reservoir')
    op.drop_index(op.f('ix_pipeline_target_node_id'), table_name='pipeline')
    op.drop_index(op.f('ix_pipeline_status'), table_name='pipeline')
    op.drop_index(op.f('ix_pipeline_source_node_id'), table_name='pipeline')
    op.drop_index('ix_pipeline_route', table_name='pipeline', postgresql_using='gist')
    op.drop_table('pipeline')
    op.drop_index(op.f('ix_demand_zone_priority'), table_name='demand_zone')
    op.drop_index('ix_demand_zone_boundary', table_name='demand_zone', postgresql_using='gist')
    op.drop_table('demand_zone')
    op.drop_index(op.f('ix_network_node_status'), table_name='network_node')
    op.drop_index(op.f('ix_network_node_node_type'), table_name='network_node')
    op.drop_index('ix_network_node_location', table_name='network_node', postgresql_using='gist')
    op.drop_table('network_node')
    # ### end Alembic commands ###

    # Autogenerate does not emit DROP TYPE for shared/unshared enums; drop
    # them explicitly now that every referencing table is gone.
    bind = op.get_bind()
    sa.Enum(name='facility_type').drop(bind, checkfirst=True)
    sa.Enum(name='tanker_status').drop(bind, checkfirst=True)
    sa.Enum(name='water_quality').drop(bind, checkfirst=True)
    sa.Enum(name='priority_level').drop(bind, checkfirst=True)
    sa.Enum(name='zone_type').drop(bind, checkfirst=True)
    sa.Enum(name='asset_status').drop(bind, checkfirst=True)
    sa.Enum(name='node_type').drop(bind, checkfirst=True)
